### ISSUE TITLE
boost context

### ISSUE THREAD

**Issue by liangshiweigithub** [atnaguzin/Boost-for-Android-Prebuilt#1]
why didn't you offer a prebuilt library for boost_context in armeabi and armeabi-v7a in boost version 1.61.0. I am looking forward for you reply. Thanks very much.

**Comment by atnaguzin** [comment]
I really don't know, why it doesnt compiled.
I had error, when compiling context library:
`...skipped <pstage/lib>libboost_context.a for lack of <pbin.v2/libs/context/build/gcc-arm/release/link-static/target-os-android/threading-multi>libboost_context.a...`

**Comment by atnaguzin** [comment]
Yup, really, libbost_context not supported by android and some other platforms.
But I found that [link](http://stackoverflow.com/questions/26668858/how-to-build-boost-1-56-0-boostcontext-for-iphone-arm).
Here one warriat of solving that problem. I added some lines, and it compiled. I rebuild all libraries, but hope that you will check it in your project,
